// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: mojang/mojang.proto

package mojang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mojang_GetProfile_FullMethodName = "/Mojang/GetProfile"
)

// MojangClient is the client API for Mojang service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MojangClient interface {
	GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileReponse, error)
}

type mojangClient struct {
	cc grpc.ClientConnInterface
}

func NewMojangClient(cc grpc.ClientConnInterface) MojangClient {
	return &mojangClient{cc}
}

func (c *mojangClient) GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileReponse)
	err := c.cc.Invoke(ctx, Mojang_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MojangServer is the server API for Mojang service.
// All implementations must embed UnimplementedMojangServer
// for forward compatibility.
type MojangServer interface {
	GetProfile(context.Context, *ProfileRequest) (*ProfileReponse, error)
	mustEmbedUnimplementedMojangServer()
}

// UnimplementedMojangServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMojangServer struct{}

func (UnimplementedMojangServer) GetProfile(context.Context, *ProfileRequest) (*ProfileReponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedMojangServer) mustEmbedUnimplementedMojangServer() {}
func (UnimplementedMojangServer) testEmbeddedByValue()                {}

// UnsafeMojangServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MojangServer will
// result in compilation errors.
type UnsafeMojangServer interface {
	mustEmbedUnimplementedMojangServer()
}

func RegisterMojangServer(s grpc.ServiceRegistrar, srv MojangServer) {
	// If the following call panics, it indicates UnimplementedMojangServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mojang_ServiceDesc, srv)
}

func _Mojang_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MojangServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mojang_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MojangServer).GetProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mojang_ServiceDesc is the grpc.ServiceDesc for Mojang service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mojang_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Mojang",
	HandlerType: (*MojangServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _Mojang_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mojang/mojang.proto",
}
