// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mojang/mojang.proto

package mojang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_mojang_mojang_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mojang_mojang_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_mojang_mojang_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProfileReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReponse) Reset() {
	*x = ProfileReponse{}
	mi := &file_mojang_mojang_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReponse) ProtoMessage() {}

func (x *ProfileReponse) ProtoReflect() protoreflect.Message {
	mi := &file_mojang_mojang_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReponse.ProtoReflect.Descriptor instead.
func (*ProfileReponse) Descriptor() ([]byte, []int) {
	return file_mojang_mojang_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileReponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileReponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_mojang_mojang_proto protoreflect.FileDescriptor

const file_mojang_mojang_proto_rawDesc = "" +
	"\n" +
	"\x13mojang/mojang.proto\"$\n" +
	"\x0eProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x0eProfileReponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id28\n" +
	"\x06Mojang\x12.\n" +
	"\n" +
	"GetProfile\x12\x0f.ProfileRequest\x1a\x0f.ProfileReponseb\x06proto3"

var (
	file_mojang_mojang_proto_rawDescOnce sync.Once
	file_mojang_mojang_proto_rawDescData []byte
)

func file_mojang_mojang_proto_rawDescGZIP() []byte {
	file_mojang_mojang_proto_rawDescOnce.Do(func() {
		file_mojang_mojang_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mojang_mojang_proto_rawDesc), len(file_mojang_mojang_proto_rawDesc)))
	})
	return file_mojang_mojang_proto_rawDescData
}

var file_mojang_mojang_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mojang_mojang_proto_goTypes = []any{
	(*ProfileRequest)(nil), // 0: ProfileRequest
	(*ProfileReponse)(nil), // 1: ProfileReponse
}
var file_mojang_mojang_proto_depIdxs = []int32{
	0, // 0: Mojang.GetProfile:input_type -> ProfileRequest
	1, // 1: Mojang.GetProfile:output_type -> ProfileReponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mojang_mojang_proto_init() }
func file_mojang_mojang_proto_init() {
	if File_mojang_mojang_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mojang_mojang_proto_rawDesc), len(file_mojang_mojang_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mojang_mojang_proto_goTypes,
		DependencyIndexes: file_mojang_mojang_proto_depIdxs,
		MessageInfos:      file_mojang_mojang_proto_msgTypes,
	}.Build()
	File_mojang_mojang_proto = out.File
	file_mojang_mojang_proto_goTypes = nil
	file_mojang_mojang_proto_depIdxs = nil
}
